#!/usr/bin/env python3
"""Stage files from archive_bundle_plan.json into upload-ready directories."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path


SCRIPTS = Path(__file__).resolve().parent
OVERLEAF = SCRIPTS.parent
ROOT = OVERLEAF.parent
DEFAULT_PLAN = OVERLEAF / "archive_bundle_plan.json"
DEFAULT_OUTPUT = OVERLEAF / "archive_staging"


def load_plan(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def guard_clean_target(output: Path) -> None:
    resolved = output.resolve()
    forbidden = {Path("/").resolve(), OVERLEAF.resolve(), ROOT.resolve(), ROOT.parent.resolve()}
    if resolved in forbidden:
        raise ValueError(f"Refusing to clean unsafe output directory: {resolved}")


def selected_bundle_names(plan: dict, requested: list[str]) -> list[str]:
    available = sorted(plan.get("bundles", {}))
    if not requested:
        return available
    missing = sorted(set(requested) - set(available))
    if missing:
        raise ValueError("Unknown bundles: " + ", ".join(missing))
    return [name for name in available if name in set(requested)]


def stage_plan(
    plan: dict,
    plan_path: Path,
    output: Path,
    bundle_names: list[str],
    include_optional: bool,
    dry_run: bool,
    clean: bool,
) -> dict:
    if not plan.get("ready_for_archive"):
        missing = plan.get("required_missing", [])
        unknown = plan.get("unknown_categories", [])
        raise ValueError(f"Bundle plan is not ready: required_missing={missing}; unknown_categories={unknown}")

    if clean and not dry_run and output.exists():
        guard_clean_target(output)
        shutil.rmtree(output)

    staged_at = datetime.now(timezone.utc).isoformat()
    summary = {
        "created_utc": staged_at,
        "dry_run": dry_run,
        "output": str(output),
        "source_plan": str(plan_path),
        "bundles": {},
        "file_count": 0,
        "total_size_bytes": 0,
    }

    for bundle_name in bundle_names:
        bundle = plan["bundles"][bundle_name]
        files = []
        for item in bundle["files"]:
            if not item.get("required", False) and not include_optional:
                continue
            if not item.get("exists", False):
                continue
            source = Path(item["source_path"])
            destination = output / bundle_name / item["archive_path"]
            files.append(
                {
                    "archive_path": item["archive_path"],
                    "source_path": str(source),
                    "destination_path": str(destination),
                    "size_bytes": int(item.get("size_bytes", 0)),
                    "sha256": item.get("sha256"),
                    "required": bool(item.get("required")),
                    "note": item.get("note", ""),
                }
            )
            if not dry_run:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)

        bundle_summary = {
            "file_count": len(files),
            "total_size_bytes": sum(item["size_bytes"] for item in files),
            "files": files,
        }
        summary["bundles"][bundle_name] = bundle_summary
        summary["file_count"] += bundle_summary["file_count"]
        summary["total_size_bytes"] += bundle_summary["total_size_bytes"]

        if not dry_run:
            manifest_path = output / bundle_name / "bundle_manifest.json"
            manifest_path.write_text(json.dumps(bundle_summary, indent=2) + "\n", encoding="utf-8")

    if not dry_run:
        output.mkdir(parents=True, exist_ok=True)
        (output / "archive_bundle_plan.json").write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
        (output / "archive_staging_summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Stage archive bundles from archive_bundle_plan.json.")
    parser.add_argument("--plan", type=Path, default=DEFAULT_PLAN, help="Bundle plan JSON generated by plan_archive_bundle.py.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Directory that will receive staged archive bundles.")
    parser.add_argument("--bundle", action="append", default=[], help="Bundle name to stage; repeat to stage multiple bundles.")
    parser.add_argument("--include-optional", action="store_true", help="Include optional records that exist.")
    parser.add_argument("--dry-run", action="store_true", help="Summarize files without copying them.")
    parser.add_argument("--clean", action="store_true", help="Remove the output directory before staging.")
    args = parser.parse_args()

    try:
        plan = load_plan(args.plan)
        bundles = selected_bundle_names(plan, args.bundle)
        summary = stage_plan(plan, args.plan, args.output, bundles, args.include_optional, args.dry_run, args.clean)
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, indent=2), file=sys.stderr)
        return 1

    print(
        json.dumps(
            {
                "ok": True,
                "dry_run": summary["dry_run"],
                "output": summary["output"],
                "file_count": summary["file_count"],
                "total_size_bytes": summary["total_size_bytes"],
                "bundles": {name: item["file_count"] for name, item in summary["bundles"].items()},
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
